obj-m += linear.o
all:
	make -C /home/josteda99/Documents/CompetiveCode/SO/SO/Ejercicio3/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /home/josteda99/Documents/CompetiveCode/SO/SO/Ejercicio3/$(shell uname -r)/build M=$(PWD) clean
